# Generated by Django 4.1.6 on 2023-02-09 13:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
        migrations.AddField(
            model_name="product",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка"),
        ),
        migrations.AddField(
            model_name="product",
            name="pubdate",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время создания товара"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="text",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/", verbose_name="Фото товара"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Название товара"
            ),
        ),
    ]
