# Generated by Django 4.1.6 on 2023-02-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_options_remove_product_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorySeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="category_season_name"
                    ),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Цена товара"),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=8, verbose_name="Размер"),
        ),
        migrations.AddField(
            model_name="product",
            name="category_season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.categoryseason",
                verbose_name="category_season",
            ),
        ),
    ]
