# Generated by Django 4.1.6 on 2023-02-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_categoryseason_product_price_product_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorySize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="category_size_name"),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="category_season",
        ),
        migrations.AddField(
            model_name="product",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.categoryseason",
                verbose_name="Сезон",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.categorysize",
                verbose_name="Размер одежды в наборе",
            ),
        ),
    ]
