# Generated by Django 4.1.6 on 2023-02-09 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_categorysize_remove_product_category_season_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.categoryseason",
                verbose_name="category_season",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                max_length=8, null=True, verbose_name="Размер одежды"
            ),
        ),
        migrations.DeleteModel(
            name="CategorySize",
        ),
    ]
